# Generated by Django 5.0.3 on 2024-04-11 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('surname', models.CharField(max_length=25)),
                ('device_tag', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_taken', models.DateTimeField(verbose_name='time taken')),
                ('heart_rate', models.IntegerField(default=0)),
                ('body_temp', models.IntegerField(default=0)),
                ('ox_saturation', models.IntegerField(default=0)),
                ('blood_pressure', models.IntegerField(default=0)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VitalGuard.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_changed', models.DateTimeField(verbose_name='time changed')),
                ('heart_rate', models.IntegerField(default=100)),
                ('body_temp', models.IntegerField(default=100)),
                ('ox_saturation', models.IntegerField(default=100)),
                ('blood_pressure', models.IntegerField(default=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VitalGuard.patient')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('type', models.CharField(choices=[('CT', 'Caretaker'), ('DR', 'Doctor')], default='DR', max_length=2)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VitalGuard.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=300)),
                ('time', models.DateField(verbose_name='date posted')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VitalGuard.patient')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VitalGuard.user')),
            ],
        ),
    ]
